// Validation harness (PROMPT B.2) — the trust differentiator.
//
// Runs against a labeled validation set, computes per-metric RMSE/MAE/ICC broken
// down by PHASE (acceleration vs top speed) and VIEWPOINT (side/oblique/head-on),
// and gates each (metric, viewpoint) cell: error over threshold => 'experimental'
// in the UI rather than 'trusted'. We do NOT invent confidence — the in-app bands
// are grounded in these errors.

import { mae, rmse, icc } from './metrics.js';

export type Phase = 'acceleration' | 'max_velocity';
export type Viewpoint = 'side' | 'oblique' | 'head-on';
export type MetricStatus = 'trusted' | 'experimental';

export interface ValidationSample {
  clipId: string;
  phase: Phase;
  viewpoint: Viewpoint;
  truth: Record<string, number>;
  predicted: Record<string, number>;
}

export const METRIC_KEYS = ['trunk_lean', 'knee_drive', 'hip_extension', 'contact_time_ms', 'cadence_spm'] as const;
export type MetricKey = (typeof METRIC_KEYS)[number];

/** Allowed error (MAE) before a metric is downgraded to 'experimental'. */
export const ERROR_THRESHOLDS: Record<MetricKey, number> = {
  trunk_lean: 4, // deg
  knee_drive: 5, // deg
  hip_extension: 5, // deg
  contact_time_ms: 12, // ms
  cadence_spm: 6, // spm
};

export interface CellResult {
  metric: MetricKey;
  phase: Phase;
  viewpoint: Viewpoint;
  n: number;
  mae: number;
  rmse: number;
  icc: number;
  status: MetricStatus;
}

export interface ValidationReport {
  cells: CellResult[];
  /** Overall per-metric status: trusted only if every viewpoint passes. */
  perMetricStatus: Record<MetricKey, MetricStatus>;
  knownWeakCases: string[];
}

const round = (x: number, d = 2) => Math.round(x * 10 ** d) / 10 ** d;

/** Aggregate samples into per-(metric,phase,viewpoint) error cells + gate them. */
export function runValidation(samples: ValidationSample[]): ValidationReport {
  const cells: CellResult[] = [];

  for (const metric of METRIC_KEYS) {
    for (const phase of ['acceleration', 'max_velocity'] as Phase[]) {
      for (const viewpoint of ['side', 'oblique', 'head-on'] as Viewpoint[]) {
        const subset = samples.filter(
          (s) => s.phase === phase && s.viewpoint === viewpoint && metric in s.truth && metric in s.predicted
        );
        if (subset.length === 0) continue;
        const pred = subset.map((s) => s.predicted[metric]);
        const truth = subset.map((s) => s.truth[metric]);
        const m = mae(pred, truth);
        cells.push({
          metric,
          phase,
          viewpoint,
          n: subset.length,
          mae: round(m),
          rmse: round(rmse(pred, truth)),
          icc: round(icc(pred, truth)),
          status: m > ERROR_THRESHOLDS[metric] ? 'experimental' : 'trusted',
        });
      }
    }
  }

  const perMetricStatus = {} as Record<MetricKey, MetricStatus>;
  for (const metric of METRIC_KEYS) {
    const my = cells.filter((c) => c.metric === metric);
    perMetricStatus[metric] = my.some((c) => c.status === 'experimental') ? 'experimental' : 'trusted';
  }

  const knownWeakCases = cells
    .filter((c) => c.status === 'experimental')
    .map((c) => `${c.metric} @ ${c.viewpoint}/${c.phase}: MAE ${c.mae} > ${ERROR_THRESHOLDS[c.metric]}`);

  return { cells, perMetricStatus, knownWeakCases };
}

/** UI gate: is this metric, measured from this viewpoint, safe to show as trusted? */
export function metricStatus(report: ValidationReport, metric: MetricKey, viewpoint: Viewpoint): MetricStatus {
  const cell = report.cells.find((c) => c.metric === metric && c.viewpoint === viewpoint);
  return cell?.status ?? 'experimental'; // unknown => not trusted
}

export function buildReportMarkdown(report: ValidationReport): string {
  const lines: string[] = [];
  lines.push('# Stride Biomechanics — Validation Report');
  lines.push('');
  lines.push('> Generated by `scripts/validate-biomech`. Errors below are the basis for the');
  lines.push('> in-app confidence bands. A cell over its threshold is shown as **experimental**,');
  lines.push('> never as a trusted number. We do not invent confidence.');
  lines.push('');
  lines.push('| Metric | Phase | Viewpoint | n | MAE | RMSE | ICC | Status |');
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const c of report.cells) {
    lines.push(
      `| ${c.metric} | ${c.phase} | ${c.viewpoint} | ${c.n} | ${c.mae} | ${c.rmse} | ${c.icc} | ${
        c.status === 'experimental' ? '⚠️ experimental' : '✅ trusted'
      } |`
    );
  }
  lines.push('');
  lines.push('## Per-metric status (trusted only if every viewpoint passes)');
  lines.push('');
  for (const [k, v] of Object.entries(report.perMetricStatus)) {
    lines.push(`- **${k}**: ${v === 'experimental' ? '⚠️ experimental' : '✅ trusted'} (threshold MAE ${ERROR_THRESHOLDS[k as MetricKey]})`);
  }
  lines.push('');
  lines.push('## Known weak cases (honest limits)');
  lines.push('');
  if (report.knownWeakCases.length === 0) {
    lines.push('_None over threshold in this run._');
  } else {
    for (const w of report.knownWeakCases) lines.push(`- ${w}`);
  }
  lines.push('');
  lines.push('Consistent with the literature: sprinting pelvis/hip kinematics — especially at');
  lines.push('TOP SPEED and from head-on views — are the hardest to recover. We validate on');
  lines.push('sprinting and do NOT borrow gait accuracy numbers.');
  lines.push('');
  return lines.join('\n');
}
