INSERT INTO reference_drills (key, name, description, video_url, cues, contraindications, target_metrics) VALUES
('a_skips', 'A-Skips', 'High-knee marching drill for knee drive improvement', 'https://cdn.stride.ai/drills/a-skips.mp4', '["Punch foot down under hip","Drive knee to 90°","Stay tall through hips"]', '["knee_pain","hip_flexor_strain"]', '["knee_drive_angle"]'),
('wall_drills', 'Wall Drills (1-2-3 Switch)', 'Static wall drive for acceleration mechanics', 'https://cdn.stride.ai/drills/wall-drills.mp4', '["Step over opposite knee","Full hip extension","Maintain flat back"]', '["lower_back_pain"]', '["hip_extension","knee_drive_angle"]'),
('standing_arm_swings', 'Standing Arm Swings', 'Isolated arm mechanics drill', 'https://cdn.stride.ai/drills/arm-swings.mp4', '["Pocket to chin","Drive elbow straight back","Relax hands"]', '[]', '["arm_angle"]'),
('sled_pulls', 'Resisted Sled Pulls', 'Loaded acceleration for power development', 'https://cdn.stride.ai/drills/sled-pulls.mp4', '["Lean into harness 45°","Powerful triple extension","Short quick steps"]', '["hamstring_strain","achilles_injury"]', '["hip_extension","torso_lean"]'),
('b_skips', 'B-Skips', 'Extended A-skip with pawback for stride mechanics', 'https://cdn.stride.ai/drills/b-skips.mp4', '["Cycle through full ROM","Pawback before ground contact","Maintain upright posture"]', '["knee_pain"]', '["knee_drive_angle","overstriding"]'),
('ankle_stiffness', 'Ankle Stiffness Jumps', 'Rapid ground contact for reactive strength', 'https://cdn.stride.ai/drills/ankle-jumps.mp4', '["Minimal ground contact time","Land mid-foot","Keep knees soft not bent"]', '["ankle_sprain","plantar_fasciitis"]', '["ground_contact_time"]'),
('hip_circles', 'Hip Mobility Circles', 'Dynamic hip flexor and rotator mobilization', 'https://cdn.stride.ai/drills/hip-circles.mp4', '["Full range of motion","Control the movement","Equal reps each side"]', '["hip_labrum_tear"]', '["hip_extension"]'),
('power_skips', 'Power Skips', 'Explosive vertical drive for stride length', 'https://cdn.stride.ai/drills/power-skips.mp4', '["Maximum height per skip","Full arm drive","Land softly"]', '["shin_splints"]', '["knee_drive_angle","hip_extension"]'),
('wicket_runs', 'Wicket Runs', 'Stride length and frequency drill with hurdles', 'https://cdn.stride.ai/drills/wicket-runs.mp4', '["Consistent stride pattern","High hips","Relax at speed"]', '["hamstring_tightness"]', '["overstriding","knee_drive_angle"]'),
('torso_lean_march', 'Lean March', 'Forward lean and posture drill for acceleration', 'https://cdn.stride.ai/drills/lean-march.mp4', '["Lean from ankles not waist","Drive arms aggressively","Look 10m ahead"]', '[]', '["torso_lean"]');
